base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  # password: kenrome001
  # port: 3301
  # host: 127.0.0.1
  host: localhost
  database: suoma

development:
  <<: *base

test:
  <<: *base
production:
  <<: *base
